
'use strict';
(()=>{
const canvas=document.getElementById('world'), overlay=document.getElementById('overlay'), ctx=overlay.getContext('2d');
const $=id=>document.getElementById(id), TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), lerp=(a,b,t)=>a+(b-a)*t, hypot=Math.hypot, rand=(a,b)=>a+Math.random()*(b-a), dist=(a,b)=>hypot(a.x-b.x,a.z-b.z);
const nativeGL=canvas.getContext('webgl2',{alpha:false,antialias:true,powerPreference:'high-performance'});
const softwareContext=nativeGL?null:canvas.getContext('2d');
const gl=nativeGL||new Proxy({}, {get(_,key){if(/^[A-Z_0-9]+$/.test(String(key)))return 0;if(key==='getShaderParameter'||key==='getProgramParameter')return ()=>true;return ()=>null;}});
if(!nativeGL&&!softwareContext){$('error').hidden=false;return;}
const v3=(x=0,y=0,z=0)=>[x,y,z];
function norm(a){let n=hypot(...a)||1;return a.map(x=>x/n)}
const sub=(a,b)=>a.map((x,i)=>x-b[i]), cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]], dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
function matmul(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function look(eye,target){let z=norm(sub(eye,target)),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);}
const ortho=(l,r,b,t,n,f)=>new Float32Array([2/(r-l),0,0,0,0,2/(t-b),0,0,0,0,-2/(f-n),0,-(r+l)/(r-l),-(t+b)/(t-b),-(f+n)/(f-n),1]);
function program(vs,fs){let p=gl.createProgram();for(const [type,src] of [[gl.VERTEX_SHADER,vs],[gl.FRAGMENT_SHADER,fs]]){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));gl.attachShader(p,s);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
const vertex=`#version 300 es
precision highp float;
layout(location=0) in vec3 pos;layout(location=1) in vec3 normal;
layout(location=2) in vec3 offset;layout(location=3) in vec3 scale;
layout(location=4) in float angle;layout(location=5) in vec4 color;
uniform mat4 vp;uniform mat4 lightVP;
out vec3 N;out vec4 C;out vec4 S;out vec3 W;
void main(){float c=cos(angle),s=sin(angle);mat3 r=mat3(c,0.,-s,0.,1.,0.,s,0.,c);vec3 w=r*(pos*scale)+offset;W=w;N=normalize(r*(normal/scale));C=color;S=lightVP*vec4(w,1.);gl_Position=vp*vec4(w,1.);}`;
const fragment=`#version 300 es
precision highp float;
in vec3 N;in vec4 C;in vec4 S;in vec3 W;uniform sampler2D shadowMap;out vec4 outColor;
void main(){vec3 n=normalize(N);vec3 l=normalize(vec3(-.5,.9,.5));float diff=max(dot(n,l),0.);vec3 q=S.xyz/S.w*.5+.5;float shadow=0.;
if(q.x>0.&&q.x<1.&&q.y>0.&&q.y<1.&&q.z<1.){float bias=max(.0018,.0028*(1.-diff));for(int x=0;x<=1;x++)for(int y=0;y<=1;y++)shadow+=(q.z-bias>texture(shadowMap,q.xy+(vec2(x,y)-.5)/1024.).r)?1.:0.;shadow/=4.;}
vec3 amb=mix(vec3(.49,.59,.66),vec3(.74,.79,.82),n.y*.5+.5);vec3 light=amb+vec3(.34,.29,.22)*diff*(1.-shadow*.88);vec3 col=C.rgb*light;col=mix(col,C.rgb,C.a);outColor=vec4(col,1.);}`;
const depthFrag=`#version 300 es
precision highp float;out vec4 c;void main(){c=vec4(1.);}`;
let shader,depthShader;
try{shader=program(vertex,fragment);depthShader=program(vertex,depthFrag);}catch(e){$('error').hidden=false;$('errorDetail').textContent=String(e);return;}
const geom={};
function makeGeom(name,arr){let vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(arr),gl.STATIC_DRAW);geom[name]={vb,n:arr.length/6,static:[],dynamic:[],sb:gl.createBuffer(),db:gl.createBuffer()};}
function tri(arr,a,b,c,na=null,nb=null,nc=null){let n=na||norm(cross(sub(b,a),sub(c,a)));arr.push(...a,...n,...b,...(nb||n),...c,...(nc||n));}
let ar=[];const faces=[[[1,0,0],[.5,-.5,-.5],[.5,.5,-.5],[.5,.5,.5],[.5,-.5,.5]],[[-1,0,0],[-.5,-.5,.5],[-.5,.5,.5],[-.5,.5,-.5],[-.5,-.5,-.5]],[[0,1,0],[-.5,.5,-.5],[-.5,.5,.5],[.5,.5,.5],[.5,.5,-.5]],[[0,-1,0],[-.5,-.5,.5],[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5]],[[0,0,1],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5],[-.5,-.5,.5]],[[0,0,-1],[-.5,-.5,-.5],[-.5,.5,-.5],[.5,.5,-.5],[.5,-.5,-.5]]];
for(let f of faces){tri(ar,f[1],f[2],f[3],f[0]);tri(ar,f[1],f[3],f[4],f[0]);}makeGeom('box',ar);
ar=[];let spherePoint=(lat,lon)=>[Math.sin(lat)*Math.cos(lon)*.5,Math.cos(lat)*.5,Math.sin(lat)*Math.sin(lon)*.5];for(let i=0;i<8;i++)for(let j=0;j<12;j++){let a=spherePoint(Math.PI*i/8,TAU*j/12),b=spherePoint(Math.PI*(i+1)/8,TAU*j/12),c=spherePoint(Math.PI*(i+1)/8,TAU*(j+1)/12),d=spherePoint(Math.PI*i/8,TAU*(j+1)/12);tri(ar,a,b,c,norm(a),norm(b),norm(c));tri(ar,a,c,d,norm(a),norm(c),norm(d));}makeGeom('ball',ar);
for(let cone of [false,true]){ar=[];for(let i=0;i<16;i++){let a=i/16*TAU,b=(i+1)/16*TAU,A=[Math.cos(a)*.5,-.5,Math.sin(a)*.5],B=[Math.cos(b)*.5,-.5,Math.sin(b)*.5],C=cone?[0,.5,0]:[B[0],.5,B[2]],D=cone?C:[A[0],.5,A[2]];if(!cone)tri(ar,A,D,C);tri(ar,A,C,B);tri(ar,[0,-.5,0],A,B,[0,-1,0]);if(!cone)tri(ar,[0,.5,0],C,D,[0,1,0]);}makeGeom(cone?'cone':'cyl',ar);}
const colors=new Map();function rgb(c){if(!colors.has(c)){let h=parseInt(c.replace('#',''),16);colors.set(c,[(h>>16&255)/255,(h>>8&255)/255,(h&255)/255]);}return colors.get(c);}
let buildingStatic=false;
function mesh(type,x,y,z,sx,sy,sz,color,yaw=0,unlit=0){let a=buildingStatic?geom[type].static:geom[type].dynamic;a.push(x,y,z,Math.max(.002,sx),Math.max(.002,sy),Math.max(.002,sz),yaw,...rgb(color),unlit);}
const box=(x,y,z,sx,sy,sz,c,a=0,u=0)=>mesh('box',x,y,z,sx,sy,sz,c,a,u), ball=(x,y,z,sx,sy,sz,c,a=0,u=0)=>mesh('ball',x,y,z,sx,sy,sz,c,a,u), cyl=(x,y,z,sx,sy,sz,c,a=0,u=0)=>mesh('cyl',x,y,z,sx,sy,sz,c,a,u), cone=(x,y,z,sx,sy,sz,c)=>mesh('cone',x,y,z,sx,sy,sz,c);
let shadow=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,shadow);gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,1024,1024,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);let fbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,fbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,shadow,0);gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);gl.bindFramebuffer(gl.FRAMEBUFFER,null);
const lightVP=matmul(ortho(-29,29,-31,31,1,85),look([-20,38,22],[0,0,-2]));
function bindGeom(g,buf){gl.bindBuffer(gl.ARRAY_BUFFER,g.vb);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,24,12);gl.bindBuffer(gl.ARRAY_BUFFER,buf);for(let [i,size,off] of [[2,3,0],[3,3,3],[4,1,6],[5,4,7]]){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,size,gl.FLOAT,false,44,off*4);gl.vertexAttribDivisor(i,1);}}
function drawPass(p,v){gl.useProgram(p);gl.uniformMatrix4fv(gl.getUniformLocation(p,'vp'),false,v);gl.uniformMatrix4fv(gl.getUniformLocation(p,'lightVP'),false,lightVP);if(p===shader){gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,shadow);gl.uniform1i(gl.getUniformLocation(p,'shadowMap'),0);}for(let g of Object.values(geom)){if(g.static.length){bindGeom(g,g.sb);gl.drawArraysInstanced(gl.TRIANGLES,0,g.n,g.static.length/11);}if(g.dynamic.length){bindGeom(g,g.db);gl.drawArraysInstanced(gl.TRIANGLES,0,g.n,g.dynamic.length/11);}}}
let W=1,H=1,DPR=1,vp,cam={x:0,z:-2},yaw=-.32,elev=.94,span=17.2;
function camera(){let asp=W/H;span=asp<.82?13.0/asp:17.2;let l=36,eye=[cam.x+Math.sin(yaw)*Math.cos(elev)*l,Math.sin(elev)*l,cam.z+Math.cos(yaw)*Math.cos(elev)*l];vp=matmul(ortho(-span*asp/2,span*asp/2,-span/2,span/2,1,90),look(eye,[cam.x,0,cam.z]));}
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);overlay.width=Math.round(W*DPR);overlay.height=Math.round(H*DPR);camera();}
addEventListener('resize',resize);resize();
function project(x,y,z){return {x:(vp[0]*x+vp[4]*y+vp[8]*z+vp[12]+1)*W/2,y:(1-vp[1]*x-vp[5]*y-vp[9]*z-vp[13])*H/2};}
function unproject(x,y){let sx=(x/W-.5)*span*W/H,sz=(y/H-.5)*span/Math.sin(elev);return {x:cam.x+Math.cos(yaw)*sx+Math.sin(yaw)*sz,z:cam.z-Math.sin(yaw)*sx+Math.cos(yaw)*sz};}
// Campaign state and inventory. One saved snapshot contains BOTH local and lasting progress.
const KEY='shiokaze_workshop_v3', LEGACY_KEY='snowcamp_direct_v2_1';
const STAGES=[
 {name:'はじまりの浜',goal:'小舟を直す',target:72,orders:0,sea:'#5db7b9',grass:'#9fbf76',story:'漂着した資材から、小舟の修理部品をつくろう。',done:'小舟が海へ。島の工房は、住民に引き継がれました。',relic:'帆のかけら',nodes:[[-4,-4],[-1,-3],[-6,-1]],mill:{x:-4,z:2},drop:{x:-2.8,z:3.4},sell:{x:4.5,z:2.5},cash:{x:6,z:4},repair:{x:1.4,z:-4.5},monument:{x:2,z:-6.5}},
 {name:'運河の港',goal:'水門を直す',target:96,orders:0,sea:'#63a7b9',grass:'#94b383',story:'資材は運河の向こう。東の橋を回るか、近道を直すか。',done:'水門が動き出し、港にふたたび水が流れます。',relic:'水門の歯車',nodes:[[-5,-5],[-1,-6],[3,-4.5]],mill:{x:-4,z:3},drop:{x:-2.8,z:4.2},sell:{x:4.5,z:3.1},cash:{x:6.5,z:4.5},repair:{x:1.5,z:-4},monument:{x:2,z:-6.5}},
 {name:'灯台の島',goal:'灯台をともす',target:112,orders:3,sea:'#568da9',grass:'#b2ba7d',story:'部品で灯台を修理。青い桟橋では、注文船にも届けよう。',done:'3つの島に灯がともりました。あなたの航海の、ひとつの完成です。',relic:'灯台のレンズ',nodes:[[-5,-5],[-2,-3.5],[-6,-1]],mill:{x:-4,z:2},drop:{x:-2.8,z:3.4},sell:{x:4.5,z:2.5},cash:{x:6,z:4},repair:{x:0,z:-4.5},monument:{x:0,z:-6.6}}
];
const TOOLS={none:{name:'基本の道具',desc:'まずは身軽に、工房を始める。'},cart:{name:'大きな荷かご',desc:'持てる資材・部品が12個増える。'},press:{name:'携帯モーター',desc:'加工が40%速くなる。'},bridge:{name:'修理キット',desc:'運河では近道が開通。他の島では支度金60。'}};
const cfg=()=>STAGES[state.island];
const actor=()=>({x:0,z:3.2,yaw:0,raw:0,parts:0,walk:0,moving:false,cd:0,hit:0,mode:'gather',path:[],destKey:''});
const freshState=(island=0,tool='none')=>({island,tool,money:tool==='bridge'&&island!==1?60:island?20:0,granted:tool==='bridge'&&island!==1?60:island?20:0,pack:0,speed:0,machine:0,price:0,courier:false,gatherer:false,bridge:island===1&&tool==='bridge',hint:0,paid:{},mission:0,sold:0,earned:0,spent:0,harvested:0,counter:0,till:0,specialTill:0,specialCount:0,specialProgress:0,specialCycle:-1,elapsed:0,done:false,finishTimer:0,phase:0});
const freshMeta=()=>({completed:[false,false,false],best:[null,null,null],unlocked:['none'],sound:true,legacy:false});
let state=freshState(),meta=freshMeta(),player=actor(),gatherer=actor(),courier=actor(),mill={raw:0,parts:0,progress:0},nodes=[];
let t=0,flies=[],sparks=[],labels=[],footprints=[],rings=[],keys={},mouse=null,target=null,hasInput=false,paused=false,toastUntil=0,saveClock=0,transferClock=0,saleClock=0,lastGoal='',clearShown=false,legacyNotice=false,padTimer=0,activePad=null,lockedPads=new Set(),routeVersion=0;
let chosenIsland=0,chosenTool='none',panelMode='';
const capacity=()=>[12,24,40,60][state.pack]+(state.tool==='cart'?12:0);
const price=()=>6+state.price*3;
const orderSize=()=>[8,12,16][Math.min(2,state.specialCount)];
const cycle=()=>Math.floor(state.elapsed/45);
const orderActive=()=>state.island===2&&state.specialCount<3&&state.elapsed%45<25&&state.specialCycle!==cycle();
const special={x:6,z:-3.6}, specialCash={x:7,z:-1.7};
function makeNodes(){return cfg().nodes.map(([x,z],i)=>({x,z,id:i,left:24,regen:0,flash:0}));}
function snapshot(){const a=e=>({x:e.x,z:e.z,raw:e.raw,parts:e.parts,mode:e.mode});return {version:3,meta,state,player:a(player),gatherer:a(gatherer),courier:a(courier),mill,nodes:nodes.map(n=>({left:n.left,regen:n.regen}))};}
const num=(v,min,max)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
function validate(v){
 if(!v||v.version!==3||!v.meta||!v.state)return false;const s=v.state,m=v.meta;
 if(!Number.isInteger(s.island)||!num(s.island,0,2)||!Object.hasOwn(TOOLS,s.tool))return false;
 for(const k of ['money','granted','mission','sold','earned','spent','harvested','counter','till','specialTill','specialProgress'])if(!Number.isInteger(s[k])||!num(s[k],0,100000000))return false;
 for(const k of ['elapsed','finishTimer'])if(!num(s[k],0,1e8))return false;
 for(const [k,max] of [['pack',3],['speed',2],['machine',2],['price',2],['hint',4],['phase',3],['specialCount',3]])if(!Number.isInteger(s[k])||!num(s[k],0,max))return false;
 if(!Number.isInteger(s.specialCycle)||s.specialCycle< -1||s.mission>STAGES[s.island].target||s.counter>150)return false;
 for(const k of ['courier','gatherer','bridge','done'])if(typeof s[k]!=='boolean')return false;
 if(!s.paid||Object.getPrototypeOf(s.paid)!==Object.prototype)return false;
 for(const [k,vv] of Object.entries(s.paid))if(!['pack','speed','machine','courier','gatherer','bridge','price'].includes(k)||!Number.isInteger(vv)||!num(vv,0,5000))return false;
 if(!Array.isArray(m.completed)||m.completed.length!==3||m.completed.some(x=>typeof x!=='boolean'))return false;
 if(!Array.isArray(m.best)||m.best.length!==3||m.best.some(x=>x!==null&&!num(x,0,1e8)))return false;
 if(!Array.isArray(m.unlocked)||m.unlocked.length>4||!m.unlocked.includes('none')||m.unlocked.some(x=>!Object.hasOwn(TOOLS,x)))return false;
 if(typeof m.sound!=='boolean'||typeof m.legacy!=='boolean')return false;
 if(!v.mill||!num(v.mill.raw,0,120)||!num(v.mill.parts,0,120)||!num(v.mill.progress,0,2))return false;
 for(const k of ['player','gatherer','courier']){const e=v[k];if(!e||!num(e.x,-9,9)||!num(e.z,-9,9)||!Number.isInteger(e.raw)||!num(e.raw,0,100)||!Number.isInteger(e.parts)||!num(e.parts,0,100))return false;}
 if(!Array.isArray(v.nodes)||v.nodes.length!==3||v.nodes.some(n=>!num(n.left,0,24)||!Number.isInteger(n.left)||!num(n.regen,0,30)))return false;
 return true;
}
function load(){
 let stored=null;for(const key of [KEY,KEY+'.backup']){try{const raw=localStorage.getItem(key);if(!raw)continue;const v=JSON.parse(raw);if(!validate(v))continue;stored=v;if(key.endsWith('backup'))$('saveWarn').textContent='直前の保存から復旧しました';break;}catch(e){}}
 if(stored){const s=stored.state;Object.assign(state,freshState(s.island,s.tool));for(const k of Object.keys(state))state[k]=s[k];meta=stored.meta;nodes=makeNodes();for(let i=0;i<3;i++){nodes[i].left=stored.nodes[i].left;nodes[i].regen=stored.nodes[i].regen;}for(const [e,k] of [[player,'player'],[gatherer,'gatherer'],[courier,'courier']]){Object.assign(e,actor(),stored[k]);e.mode=['gather','drop','get','deliver'].includes(e.mode)?e.mode:'gather';}Object.assign(mill,stored.mill);return;}
 // The original save is never overwritten or deleted. Recognition is a one-time gift, not a lossy conversion.
 try{const old=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null');if(old?.state?.version===2){meta.legacy=true;meta.unlocked=['none','cart','press'];meta.sound=old.state.sound!==false;state=freshState(0,'cart');legacyNotice=true;}}catch(e){}
 nodes=makeNodes();gatherer.x=-3;gatherer.z=0;courier.x=-1;courier.z=4;courier.mode='get';
}
function save(){try{const v=snapshot();if(!validate(v)){$('saveWarn').textContent='保存できない状態です。航路の移動前に再読み込みせず確認してください';return false;}const data=JSON.stringify(v),old=localStorage.getItem(KEY);if(old){try{if(validate(JSON.parse(old)))localStorage.setItem(KEY+'.backup',old);}catch(e){}}localStorage.setItem(KEY,data);return true;}catch(e){$('saveWarn').textContent='このブラウザでは保存できません。閉じると進行が失われます';return false;}}
function resetRun(island,tool){state=freshState(island,tool);player=actor();gatherer=actor();gatherer.x=-3;gatherer.z=1;courier=actor();courier.x=-1;courier.z=4;courier.mode='get';mill={raw:0,parts:0,progress:0};nodes=makeNodes();flies=[];sparks=[];labels=[];footprints=[];rings=[];lockedPads.clear();activePad=null;padTimer=0;transferClock=0;saleClock=0;clearShown=false;clearInput();routeVersion++;cam.x=0;cam.z=0;buildStatic();cashUpdate();save();toast(cfg().story,4.5);}
function finish(){if(state.done)return;state.done=true;state.finishTimer=0;meta.completed[state.island]=true;const best=meta.best[state.island];meta.best[state.island]=best===null?state.elapsed:Math.min(best,state.elapsed);for(const tool of state.island===0?['cart','press']:state.island===1?['bridge']:[])if(!meta.unlocked.includes(tool))meta.unlocked.push(tool);buildStatic();celebrate(cfg().goal+' — 完成！',cfg().repair.x,cfg().repair.z);save();}
function unlockIndex(){return meta.completed[1]?2:meta.completed[0]?1:0;}
function cashUpdate(){$('money').textContent=Math.floor(state.money).toLocaleString('ja-JP');}
let audio;
function sound(kind){if(!meta.sound||!hasInput)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const now=audio.currentTime,osc=audio.createOscillator(),gain=audio.createGain(),f={collect:360,part:540,cash:920,pay:650,up:760}[kind]||480;osc.type='sine';osc.frequency.setValueAtTime(f,now);osc.frequency.exponentialRampToValueAtTime(f*1.35,now+.075);gain.gain.setValueAtTime(.025,now);gain.gain.exponentialRampToValueAtTime(.001,now+.13);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(now+.14);}catch(e){}}
function toast(text,duration=2.6){$('toast').textContent=text;$('toast').classList.add('show');toastUntil=t+duration;}
function textAt(text,x,z,color='#fff2bd',y=2){labels.push({text,x,z,y,life:1.2,color});if(labels.length>40)labels.shift();}
function fly(type,a,b){flies.push({type,ax:a.x,ay:a.y??1.3,az:a.z,bx:b.x,by:b.y??1.3,bz:b.z,t:0,dur:.28});if(flies.length>180)flies.shift();}
function particle(x,y,z,color,n=8){for(let i=0;i<n;i++)sparks.push({x,y,z,vx:rand(-2,2),vy:rand(2,4),vz:rand(-2,2),life:rand(.4,1.2),color,s:rand(.05,.11)});}
function celebrate(text,x,z){toast(text);sound('up');rings.push({x,z,t:0});for(const c of ['#f4cb6e','#6bccc1','#ee9b76'])particle(x,1.6,z,c,14);save();}
function addPaidUpgrade(id,x,z,title,icon,cost,show,apply){return {id,x,z,title,icon,cost,show,apply};}
const upgrades=[
 addPaidUpgrade('pack',-.5,6.3,()=> '荷かご', 'pack',()=>[40,120,300][state.pack]||0,()=>state.hint>=3&&state.pack<3,()=>{state.pack++;celebrate('一度に '+capacity()+' 個運べる！',-.5,6.3);}),
 addPaidUpgrade('speed',2.1,6.3,()=> 'モーター','gear',()=>[75,180][state.speed]||0,()=>state.hint>=3&&state.speed<2,()=>{state.speed++;celebrate('移動と回収が速くなった',2.1,6.3);}),
 addPaidUpgrade('machine',-5.7,5.7,()=> '加工台','gear',()=>[85,220][state.machine]||0,()=>state.hint>=3&&state.machine<2,()=>{state.machine++;buildStatic();celebrate('加工ラインを増設！',-5.7,5.7);}),
 addPaidUpgrade('courier',5.4,6.3,()=> '配達係','person',()=>100,()=>state.hint>=3&&!state.courier,()=>{state.courier=true;celebrate('部品の出荷は配達係へ',5.4,6.3);}),
 addPaidUpgrade('gatherer',-6.7,.4,()=> '回収係','person',()=>160,()=>state.hint>=3&&!state.gatherer,()=>{state.gatherer=true;celebrate('資材集めを任せられる！',-6.7,.4);}),
 addPaidUpgrade('bridge',-3,1.1,()=> '近道の橋','bridge',()=>90,()=>state.island===1&&!state.bridge,()=>{state.bridge=true;routeVersion++;gatherer.destKey='';courier.destKey='';player.destKey='';buildStatic();celebrate('橋がつながった！',-3,-1);}),
 addPaidUpgrade('price',7,-.2,()=> '梱包台','crate',()=>[120,280][state.price]||0,()=>state.hint>=3&&state.price<2,()=>{state.price++;buildStatic();celebrate('出荷単価 '+price()+' に！',7,-.2);})
];
function gather(e,dt,isPlayer){e.cd=Math.max(0,e.cd-dt);e.hit=Math.max(0,e.hit-dt);const cap=isPlayer?capacity():18;if(e.raw+e.parts>=cap||isPlayer&&e.parts>0)return;const n=nodes.filter(n=>n.left>0).sort((a,b)=>dist(e,a)-dist(e,b))[0];if(!n||dist(e,n)>1.55||e.cd>0)return;const amount=Math.min(4,n.left,cap-e.raw-e.parts);n.left-=amount;e.raw+=amount;state.harvested+=amount;e.cd=.52/(isPlayer?1+state.speed*.22:1);e.hit=.3;e.yaw=Math.atan2(n.x-e.x,n.z-e.z);n.flash=.15;if(n.left===0)n.regen=12;fly('raw',{x:n.x,y:.5,z:n.z},e);particle(n.x,.6,n.z,'#ecc88d',4);if(isPlayer){state.hint=Math.max(1,state.hint);sound('collect');}}
function crafting(dt){if(mill.raw>0&&mill.raw+mill.parts<=120){mill.progress+=dt*(1+state.machine*.9)*(state.tool==='press'?1.4:1);while(mill.progress>=.72&&mill.raw>0){mill.raw--;mill.parts++;mill.progress-=.72;}}else mill.progress=0;}
function transfers(dt){transferClock-=dt;if(transferClock>0)return;transferClock=.095;const c=cfg();
 if(dist(player,c.drop)<1.25){if(player.raw>0&&mill.raw+mill.parts<120){player.raw--;mill.raw++;state.hint=Math.max(2,state.hint);fly('raw',player,c.mill);}if(mill.parts>0&&player.raw+player.parts<capacity()){mill.parts--;player.parts++;fly('parts',c.mill,player);}}
 if(dist(player,c.sell)<1.15&&player.parts>0&&state.counter<150){player.parts--;state.counter++;state.hint=Math.max(3,state.hint);fly('parts',player,{x:c.sell.x+.5,y:1.2,z:c.sell.z});}
 if(dist(player,c.repair)<1.23&&player.parts>0&&state.mission<c.target){player.parts--;state.mission++;fly('parts',player,c.monument);const phase=Math.floor(state.mission/c.target*3);if(phase>state.phase){state.phase=phase;buildStatic();celebrate(phase===3?'修理部品がそろった！':'少しずつ、形になってきた',c.repair.x,c.repair.z);}if(state.mission===c.target&&state.specialCount>=c.orders)finish();}
 if(orderActive()&&dist(player,special)<1.25&&player.parts>0){player.parts--;state.specialProgress++;fly('parts',player,{x:8,z:-4,y:1});if(state.specialProgress>=orderSize()){const pay=orderSize()*price()*2;state.earned+=pay;state.specialTill+=pay;state.sold+=orderSize();state.specialCount++;state.specialProgress=0;state.specialCycle=cycle();celebrate('注文達成！ 報酬 '+pay,special.x,special.z);if(state.mission===c.target&&state.specialCount>=c.orders)finish();}}
 for(const [pos,key] of [[c.cash,'till'],[specialCash,'specialTill']])if(dist(player,pos)<1.25&&state[key]>0){const v=Math.min(18,state[key]);state[key]-=v;state.money+=v;state.hint=4;fly('cash',pos,player);sound('cash');cashUpdate();}
}
function sell(dt){saleClock-=dt;if(saleClock<=0&&state.counter>0){saleClock=.42;state.counter--;state.sold++;state.till+=price();state.earned+=price();fly('cash',{x:cfg().sell.x+2,z:cfg().sell.z},cfg().cash);}}
function staff(dt){
 if(state.gatherer){const e=gatherer;e.hit=Math.max(0,e.hit-dt);if(e.mode!=='drop'){const n=nodes.filter(n=>n.left>0).sort((a,b)=>dist(e,a)-dist(e,b))[0];if(e.raw>=16||!n&&e.raw)e.mode='drop';else if(n){if(dist(e,n)>1.4)routeTo(e,n,dt,3.8);else e.moving=false;gather(e,dt,false);}else e.moving=false;}
 if(e.mode==='drop'){e.cd=Math.max(0,e.cd-dt);if(routeTo(e,cfg().drop,dt,3.8)&&e.cd<=0){if(e.raw&&mill.raw+mill.parts<120){e.raw--;mill.raw++;e.cd=.11;fly('raw',e,cfg().mill);}if(!e.raw){e.mode='gather';e.destKey='';}}}}
 if(state.courier){const e=courier;e.cd=Math.max(0,e.cd-dt);if(e.mode!=='deliver'){const p={x:cfg().drop.x+.3,z:cfg().drop.z+.3};if(routeTo(e,p,dt,4)&&e.cd<=0){if(mill.parts>0&&e.parts<12&&!(dist(player,cfg().drop)<1.7&&player.raw+player.parts<capacity())){mill.parts--;e.parts++;e.cd=.11;fly('parts',cfg().mill,e);}if(e.parts>=10||e.parts>0&&!mill.parts){e.mode='deliver';e.destKey='';}}}else if(routeTo(e,cfg().sell,dt,4)&&e.cd<=0){if(e.parts>0&&state.counter<150){e.parts--;state.counter++;e.cd=.1;fly('parts',e,cfg().sell);}if(!e.parts){e.mode='get';e.destKey='';}}}
}
function payments(dt){if(!hasInput)return;let inside=null;for(const p of upgrades){const isin=p.show()&&dist(player,p)<.8;if(!isin)lockedPads.delete(p.id);else if(!lockedPads.has(p.id))inside=p;}if(!inside||player.moving){padTimer=0;activePad=null;return;}if(activePad!==inside.id){activePad=inside.id;padTimer=0;}padTimer+=dt;if(padTimer<.45||state.money<=0)return;const p=inside,paid=state.paid[p.id]||0,amount=Math.max(0,Math.min(state.money,p.cost()-paid,Math.ceil(p.cost()*dt)));state.money-=amount;state.spent+=amount;state.paid[p.id]=paid+amount;cashUpdate();if(Math.floor(t*15)%3===0)fly('cash',player,p);if(state.paid[p.id]>=p.cost()){delete state.paid[p.id];lockedPads.add(p.id);p.apply();save();}}
// Original coastal models use the prototype's instanced primitive renderer.
function at(e,x,y,z){const c=Math.cos(e.yaw),s=Math.sin(e.yaw);return {x:e.x+x*c+z*s,y,z:e.z-x*s+z*c};}
function part(type,e,x,y,z,sx,sy,sz,col,u=0){const p=at(e,x,y,z);mesh(type,p.x,p.y,p.z,sx,sy,sz,col,e.yaw,u);}
function item(x,y,z,finished=false,a=0,s=.65){if(finished){box(x,y,z,s,.27,s*.65,'#267c82',a);box(x,y+.15,z,s*.92,.045,s*.61,'#66bcb0',a);box(x,y+.185,z,s*.22,.025,s*.67,'#f5d491',a);box(x,y+.2,z,s*.65,.025,.1,'#f5d491',a);}else{for(let i=0;i<3;i++)box(x+(i-1)*.18*s,y+i*.035,z,s*.2,.15,s,'#c79865',a+.1);box(x,y+.15,z,s*.8,.04,.12,'#edc784',a);}}
function coin(x,y,z,a=0,s=.6){cyl(x,y,z,s,.15,s,'#d59b3e',a,.15);cyl(x,y+.09,z,s*.75,.04,s*.75,'#f5d978',a,.3);box(x,y+.12,z,.09,.02,s*.5,'#b58136',a);}
function robot(e,color='#327f8a',hero=false){const bob=e.moving?Math.abs(Math.sin(e.walk))*.06:Math.sin(t*2)*.012,w=e.moving?Math.sin(e.walk)*.15:0;for(const d of [-1,1]){part('box',e,d*.2,.2,w*d,.3,.32,.4,'#465b60');part('ball',e,d*.2,.46,w*d,.24,.35,.23,'#c6b797');}part('box',e,0,.94+bob,0,.72,.82,.56,color);part('box',e,0,1.02+bob,.3,.47,.43,.045,'#e9d9ad');part('cyl',e,0,1.4+bob,0,.32,.14,.3,'#a49f84');part('box',e,0,1.64+bob,0,.83,.46,.68,'#f1e3bd');part('box',e,0,1.64+bob,.355,.63,.2,.035,'#244c55');for(const d of [-1,1])part('ball',e,d*.17,1.64+bob,.385,.09,.095,.04,'#a8edd4',1);part('box',e,0,1.9+bob,0,.9,.07,.72,color);part('cyl',e,hero?.24:-.24,2.05+bob,0,.06,.26,.06,'#787d6b');part('ball',e,hero?.24:-.24,2.2+bob,0,.17,.17,.17,'#efb459');for(const d of [-1,1]){const swing=e.hit?Math.sin(e.hit/.3*Math.PI)*.42:w*d;part('ball',e,d*.46,1.14+bob,0,.23,.28,.26,'#a1aba2');part('box',e,d*.47,.87+bob,.09+swing,.2,.48,.22,color);part('box',e,d*.47,.65+bob,.17+swing,.26,.15,.26,'#dfcc9e');}part('box',e,0,1.0+bob,-.42,.82,.62,.4,'#956c4a');for(const d of [-1,1])part('box',e,d*.4,1.3+bob,-.4,.07,.48,.48,'#dcb77e');const n=e.raw+e.parts;for(let i=0;i<Math.min(20,n);i++){const sway=e.moving?Math.sin(t*10-i*.2)*i*.004:0,p=at(e,sway,1.37+bob+i*.19,-.45);item(p.x,p.y,p.z,i>=e.raw,e.yaw,.7);}if(hero){part('box',e,.55,.83+bob,.38,.08,.47,.08,'#73684f');part('box',e,.55,1.07+bob,.38,.34,.16,.18,'#89a9aa');}}
function palm(x,z,s=1){cyl(x,1.3*s,z,.28*s,2.6*s,.28*s,'#b7905f');for(let i=0;i<5;i++){const a=i*TAU/5;box(x+Math.sin(a)*.62*s,2.63*s,z+Math.cos(a)*.62*s,.45*s,.13*s,1.75*s,i%2?'#55957a':'#719f69',a);ball(x+Math.sin(a)*1.1*s,2.47*s,z+Math.cos(a)*1.1*s,.47*s,.2*s,.62*s,'#6f9b6c',a);}ball(x,2.62*s,z,.7*s,.34*s,.7*s,'#79a57b');}
function barrel(x,z){cyl(x,.4,z,.75,.8,.75,'#a87c51');for(const y of [.17,.65])cyl(x,y,z,.79,.09,.79,'#496b6e');cyl(x,.82,z,.69,.045,.69,'#d7b879');}
function bench(){const m=cfg().mill;for(const a of [-1,1])for(const b of [-1,1])box(m.x+a*1.2,.5,m.z+b*.45,.13,1,.13,'#476e71');box(m.x,1,m.z,3,.16,1.4,'#d6b57e');box(m.x,1.15,m.z,1.3,.18,1.05,'#347f83');for(const d of [-1,1])box(m.x+d*.56,1.75,m.z-.36,.12,1.3,.17,'#507a79');box(m.x,2.39,m.z-.36,1.4,.21,.4,'#5fa6a0');cyl(m.x,2.08,m.z-.3,.2,.7,.2,'#cbd5bf');box(m.x-.9,1.19,m.z,.55,.12,1.1,'#eece90');box(m.x+1.03,1.17,m.z,.67,.13,1.1,'#87b4a0');for(let i=0;i<state.machine;i++){box(m.x-1.35+i*.9,1.58,m.z-.58,.65,.82,.5,'#3c8d92');cyl(m.x-1.35+i*.9,2.05,m.z-.58,.44,.16,.44,'#efd38d');}barrel(m.x-2,m.z+.1);}
function boat(x,z,amount=1,s=1,a=0){const e={x,z,yaw:a};part('box',e,0,.35,0,1.3*s,.48*s,3.3*s,'#a37b51');part('box',e,0,.64,0,1.25*s,.11*s,2.7*s,'#e2bd81');for(const side of [-1,1])part('box',e,side*.6,.75,0,.13*s,.33*s,3.05*s,'#398691');part('ball',e,0,.38,1.43*s,1.3*s,.46*s,1*s,'#398691');if(amount>.3){part('cyl',e,0,1.7,0,.09*s,2.2*s,.09*s,'#8c7757');part('box',e,.43*s,2.05,.05,1*s,1.25*s,.035*s,'#ffedbe');part('box',e,.43*s,2.03,.085,1.03*s,.19*s,.04*s,'#d48564');}if(amount>.8){part('box',e,0,2.95,-.05,.62*s,.22*s,.05*s,'#efb554');part('box',e,0,.85,-.9*s,.75*s,.6*s,.8*s,'#5c9890');}}
function monument(){const m=cfg().monument,f=state.mission/cfg().target;if(state.island===0){for(let i=0;i<7;i++)box(m.x,.28,m.z-1.2+i*.43,3.4,.12,.35,'#caa675');boat(m.x,m.z,Math.max(.12,f),.85,.3);if(f<1)for(let i=0;i<3-state.phase;i++)box(m.x-1.8+i*.4,.38,m.z-1,.24,.35,1.9,'#a68257');}else if(state.island===1){box(m.x,-.01,m.z,4.2,.17,3.5,'#78b7b6');for(const d of [-1,1]){box(m.x+d*1.65,1.5,m.z,.5,3,.6,'#ceb184');box(m.x+d*1.65,3,m.z,.7,.2,.8,'#599e99');}if(f>.3)box(m.x,2.8,m.z,3.7,.38,.55,'#4d9391');if(f>.6){box(m.x,1.25,m.z,2.9,1.85,.3,'#b08a5c');for(const d of [-1,1])box(m.x+d*.8,1.3,m.z+.2,.12,1.8,.14,'#e6ca95');}if(f>=1)cyl(m.x,3.2,m.z,.85,.22,.85,'#eac56f');}else{cyl(m.x,.4,m.z,3,.7,3,'#c5bda2');cyl(m.x,.92,m.z,2.1,.72,2.1,'#f0d3a4');if(f>.3){cyl(m.x,1.85,m.z,1.75,1.2,1.75,'#e4c7a0');cyl(m.x,1.7,m.z,1.8,.3,1.8,'#d27f61');}if(f>.6){cyl(m.x,2.95,m.z,1.45,1.1,1.45,'#f4dfb7');cyl(m.x,3.55,m.z,1.8,.18,1.8,'#3c7984');for(let i=0;i<6;i++){const a=i*TAU/6;cyl(m.x+Math.sin(a)*.6,3.94,m.z+Math.cos(a)*.6,.08,.8,.08,'#466e72');}cone(m.x,4.5,m.z,2,.5,2,'#3c7984');}}}
function buildStatic(){for(const g of Object.values(geom))g.static=[];buildingStatic=true;const c=cfg();box(0,-.6,0,110,.2,110,c.sea);cyl(0,-.52,0,26,.75,25,'#c3a67c');cyl(0,-.07,0,25.3,.19,24.4,'#f1d9a5');for(const [x,z,s] of [[-6,-5,5],[5,-6,5],[-7,5,3.5],[4,6,3.5]])cyl(x,.035,z,s,.08,s,c.grass);for(let i=0;i<24;i++){const a=i*2.4,r=9.5+Math.sin(i*3)*.65,x=Math.sin(a)*r,z=Math.cos(a)*r;ball(x,.05,z,.32,.22,.45,'#e4caa0');if(i%4===0)palm(x,z,.8+(i%3)*.12);}
 for(let i=0;i<7;i++){const x=3.8+i*.8;box(x,.12,2.7,.7,.12,2.2,'#d5b37c');}for(const z of [1.8,3.6])for(const x of [5,7,9]){cyl(x,.34,z,.16,.8,.16,'#9a7959');cyl(x,.78,z,.22,.1,.22,'#e6cd95');}
 if(state.island===1){box(0,.055,-1,23,.045,1.7,c.sea);for(const z of [-1.95,-.06])box(0,.11,z,17,.17,.19,'#cbb688');for(const x of state.bridge?[5.4,-3]:[5.4]){for(let j=0;j<7;j++)box(x,.2,-1.95+j*.32,1.5,.15,.28,'#c7a577');for(const dx of [-.72,.72])for(const z of [-2,.05])cyl(x+dx,.5,z,.12,.86,.12,'#8f8763');}if(!state.bridge){for(const z of [-2,.12]){box(-3,.18,z,1.6,.15,.45,'#b7996d');box(-3,.55,z,1.4,.22,.06,'#e3b273');}}}
 bench();const s=c.sell;box(s.x+1.3,.48,s.z,1.55,.9,1.4,'#b89867');box(s.x+1.3,.96,s.z,1.8,.12,1.55,'#eac78b');for(const d of [-1,1])box(s.x+1.3+d*.65,.5,s.z+.75,.08,.85,.06,'#397c81');for(let i=0;i<state.price;i++)box(s.x+1.35,1.35+i*.4,s.z-.25,.8,.32,.8,'#71a298');monument();if(state.island===2){for(let i=0;i<6;i++)box(6+i*.55,.17,-4,.46,.1,1.9,'#9dbaad');for(const z of [-5,-3])box(7.5,.3,z,4,.2,.16,'#4c8f96');}
 // Small material details establish a coherent non-winter palette.
 for(const [x,z] of [[-7,3.8],[-6.6,7],[3.5,-7.5]]){barrel(x,z);box(x+.6,.22,z+.3,.55,.45,.55,'#b6a67c');}for(const g of Object.values(geom)){gl.bindBuffer(gl.ARRAY_BUFFER,g.sb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(g.static),gl.STATIC_DRAW);}buildingStatic=false;}
function drawDynamic(){const c=cfg();for(const n of nodes){const count=Math.ceil(n.left/4);for(let i=0;i<count;i++){box(n.x+(i%3-1)*.38,.25+Math.floor(i/3)*.21,n.z,.26,.22,1.2,n.flash?'#ffe6aa':'#a88355',.2*(i%2));}if(!n.left){cyl(n.x,.16,n.z,1.25,.045,1.25,'#d7caa0');}else{box(n.x,.32,n.z,.13,.6,1.23,'#e9c691');}}
 for(const p of upgrades){if(!p.show())continue;const near=dist(player,p)<.9;cyl(p.x,.17,p.z,2,.11,2,near?'#efc778':'#ddc597');cyl(p.x,.24,p.z,1.8,.04,1.8,near?'#fff0b3':'#f7e5bb');const paid=state.paid[p.id]||0;if(paid)for(let i=0;i<Math.floor(paid/p.cost()*12);i++){const a=i*TAU/12;box(p.x+Math.sin(a)*.86,.3,p.z+Math.cos(a)*.86,.15,.05,.15,'#4d9990',a);}}
 for(const [p,col] of [[c.drop,'#80b6a6'],[c.sell,'#deb66c'],[c.repair,'#e8a27a'],...(state.island===2?[[special,orderActive()?'#8bdde1':'#92b7b9']]:[])]){cyl(p.x,.18,p.z,2.1,.025,2.1,col);cyl(p.x,.197,p.z,1.82,.02,1.82,'#f0d6a1');}
 for(let i=0;i<Math.min(9,mill.raw);i++)item(c.mill.x-1,.3+1+i*.12,c.mill.z,false,0,.6);for(let i=0;i<Math.min(12,mill.parts);i++)item(c.mill.x+1.05,1.15+i*.16,c.mill.z,true,0,.62);if(mill.raw){const y=1.4+Math.sin(t*8)*.18;box(c.mill.x,y,c.mill.z-.12,.85,.17,.65,'#dce0bd');item(c.mill.x,1.3,c.mill.z,true,0,.6);}
 for(let i=0;i<Math.min(12,state.counter);i++)item(c.sell.x+1.3,1.1+i*.16,c.sell.z,true,0,.62);
 for(const [p,num] of [[c.cash,state.till],[specialCash,state.specialTill]])for(let i=0;i<Math.min(22,Math.ceil(num/12));i++)coin(p.x+(i%3-1)*.3,.25+Math.floor(i/6)*.13,p.z+(Math.floor(i/3)%2)*.32,0,.38);
 const bob=Math.sin(t*1.8)*.06;boat(9.2,4.6+bob,1,.7,-.7);if(state.island===2){const open=orderActive(),offset=open?0:Math.min(7,(state.elapsed%45-25)/2);if(open||state.elapsed%45>=25)boat(9+Math.max(0,offset),-4,1,.7,0);}
 if(state.island===2&&state.done){const m=c.monument;cyl(m.x,3.9,m.z,.8,.56,.8,'#ffeaa0',0,1);for(let i=0;i<2;i++){const a=t*.4+i*Math.PI;box(m.x+Math.sin(a)*1.8,3.94,m.z+Math.cos(a)*1.8,.2,.03,3.6,'#fff0b2',a,1);}}
 if(state.island===1&&state.done){const m=c.monument;for(let i=0;i<4;i++){const a=t+i*TAU/4;box(m.x+Math.sin(a)*.35,3.34,m.z+Math.cos(a)*.35,.13,.12,.7,'#eac56f',a);}}
 for(let i=0;i<22;i++){const a=i*.65,r=13.5+(i%3)*2.5;box(Math.sin(a)*r+Math.sin(t+i)*.25,-.38,Math.cos(a)*r,1.2,.018,.06,'#9ed3cf',a,.25);}
 for(let i=0;i<3;i++){const a=t*.13+i*2,x=Math.sin(a)*9,z=Math.cos(a)*9,e={x,z,yaw:a};for(const side of [-1,1])part('box',e,side*.24,4.3+Math.sin(t*3+i)*.05,0,.4,.05,.15,'#faf0d2');}
 for(const e of [player,...state.gatherer?[gatherer]:[],...state.courier?[courier]:[]])robot(e,e===player?'#347f8a':e===gatherer?'#ad7957':'#739b7b',e===player);
 for(const f of flies){const a=clamp(f.t/f.dur,0,1),x=lerp(f.ax,f.bx,a),z=lerp(f.az,f.bz,a),y=lerp(f.ay,f.by,a)+Math.sin(a*Math.PI)*1.2;if(f.type==='cash')coin(x,y,z,t*2,.45);else item(x,y,z,f.type==='parts',t,.5);}
 for(const s of sparks)box(s.x,Math.max(.15,s.y),s.z,s.s,s.s,s.s,s.color,t*3,.3);
}
function solid(x,z){if(x< -8.1||x>8.1||z< -8.1||z>8.1)return true;if(state.island===1&&z> -1.9&&z<-.08){if(Math.abs(x-5.4)>.62&&(!state.bridge||Math.abs(x+3)>.62))return true;}const m=cfg().mill,s=cfg().sell;for(const o of [{x:m.x,z:m.z,w:3.5,d:1.65},{x:s.x+1.3,z:s.z,w:1.95,d:1.7},{x:cfg().monument.x,z:cfg().monument.z,w:3.1,d:2}])if(Math.abs(x-o.x)<o.w/2+.18&&Math.abs(z-o.z)<o.d/2+.18)return true;return false;}
function move(e,dx,dz,dt,speed){const n=hypot(dx,dz);e.moving=n>.02;if(!e.moving)return;dx/=n;dz/=n;e.yaw=Math.atan2(dx,dz);const nx=e.x+dx*speed*dt,nz=e.z+dz*speed*dt;let changed=false;if(!solid(nx,e.z)){e.x=nx;changed=true;}if(!solid(e.x,nz)){e.z=nz;changed=true;}e.moving=changed;if(changed)e.walk+=dt*speed*3.2;}
// Small A* grid is used for staff and click-to-walk; drag remains entirely direct.
function pathTo(e,dest){const step=.6,N=29,grid=(x,z)=>({i:clamp(Math.round(x/step)+14,0,N-1),j:clamp(Math.round(z/step)+14,0,N-1)}),key=(i,j)=>j*N+i,pt=k=>({x:(k%N-14)*step,z:(Math.floor(k/N)-14)*step});let a=grid(e.x,e.z),b=grid(dest.x,dest.z);const start=key(a.i,a.j);let end=key(b.i,b.j);if(solid(pt(end).x,pt(end).z)){let best=Infinity;for(let dj=-3;dj<=3;dj++)for(let di=-3;di<=3;di++){let i=b.i+di,j=b.j+dj;if(i<0||j<0||i>=N||j>=N)continue;const k=key(i,j),p=pt(k),d=dist(p,dest);if(!solid(p.x,p.z)&&d<best){best=d;end=k;}}}const open=[start],came=new Map(),cost=new Map([[start,0]]),score=new Map([[start,dist(pt(start),pt(end))]]),closed=new Set();let found=false;for(let tries=0;open.length&&tries<1000;tries++){open.sort((a,b)=>score.get(a)-score.get(b));const k=open.shift();if(k===end){found=true;break;}closed.add(k);const i=k%N,j=Math.floor(k/N);for(const [di,dj] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const ni=i+di,nj=j+dj;if(ni<0||ni>=N||nj<0||nj>=N)continue;const nk=key(ni,nj),p=pt(nk);if(closed.has(nk)||solid(p.x,p.z))continue;if(di&&dj&&(solid((ni-14)*step,(j-14)*step)||solid((i-14)*step,(nj-14)*step)))continue;const g=cost.get(k)+(di&&dj?1.414:1);if(g<(cost.get(nk)??Infinity)){came.set(nk,k);cost.set(nk,g);score.set(nk,g+dist(p,pt(end))/step);if(!open.includes(nk))open.push(nk);}}}if(!found)return [];const out=[];let k=end;while(k!==start){out.unshift(pt(k));k=came.get(k);if(k===undefined)break;}if(!solid(dest.x,dest.z))out.push({x:dest.x,z:dest.z});return out;}
function routeTo(e,dest,dt,speed){if(dist(e,dest)<.22){e.moving=false;return true;}const k=`${dest.x.toFixed(1)},${dest.z.toFixed(1)},${routeVersion}`;if(e.destKey!==k){e.path=pathTo(e,dest);e.destKey=k;}while(e.path.length&&dist(e,e.path[0])<.16)e.path.shift();if(!e.path.length){e.moving=false;e.destKey='';return dist(e,dest)<1.05;}const p=e.path[0],d=dist(e,p),x=e.x,z=e.z;move(e,p.x-e.x,p.z-e.z,dt,Math.min(speed,d/dt));if(hypot(e.x-x,e.z-z)<.0001){e.destKey='';}return false;}
// Canvas 2D compatibility renderer: same world and simulation when WebGL is unavailable.
function shade(hex,f){const c=rgb(hex);return `rgb(${c.map(v=>Math.round(clamp(v*f,0,1)*255)).join(',')})`;}
function fallbackRender(){const cx=softwareContext;cx.setTransform(DPR,0,0,DPR,0,0);cx.fillStyle=cfg().sea;cx.fillRect(0,0,W,H);const list=[];for(const [type,g] of Object.entries(geom))for(const a of [g.static,g.dynamic])for(let i=0;i<a.length;i+=11){const [x,y,z,sx,sy,sz,angle,r,gr,b,u]=a.slice(i,i+11),hex='#'+[r,gr,b].map(v=>Math.round(v*255).toString(16).padStart(2,'0')).join('');list.push({type,x,y,z,sx,sy,sz,angle,hex,u,ground:y<.25&&sy<.22||sx>20,depth:x*Math.sin(yaw)+z*Math.cos(yaw)+y*.48});}list.sort((a,b)=>a.ground!==b.ground?a.ground?-1:1:a.ground?a.y-b.y:a.depth-b.depth);
 const poly=(pts,col)=>{cx.fillStyle=col;cx.beginPath();pts.forEach((p,i)=>i?cx.lineTo(p.x,p.y):cx.moveTo(p.x,p.y));cx.closePath();cx.fill();};
 for(const a of list){const co=Math.cos(a.angle),si=Math.sin(a.angle),p=(lx,ly,lz)=>project(a.x+co*lx+si*lz,a.y+ly,a.z-si*lx+co*lz);const center=p(0,0,0),radius=Math.max(a.sx,a.sy,a.sz)*H/span;if(center.x+radius<0||center.x-radius>W||center.y+radius<0||center.y-radius>H)continue;const lum=a.u?.98:.94;
 if(a.type==='box'){const sx=a.sx/2,sy=a.sy/2,sz=a.sz/2,dx=Math.sin(yaw-a.angle)>=0?1:-1,dz=Math.cos(yaw-a.angle)>=0?1:-1;poly([p(-sx,-sy,dz*sz),p(sx,-sy,dz*sz),p(sx,sy,dz*sz),p(-sx,sy,dz*sz)],shade(a.hex,lum*.83));poly([p(dx*sx,-sy,-sz),p(dx*sx,-sy,sz),p(dx*sx,sy,sz),p(dx*sx,sy,-sz)],shade(a.hex,lum*.72));poly([p(-sx,sy,-sz),p(sx,sy,-sz),p(sx,sy,sz),p(-sx,sy,sz)],shade(a.hex,lum*1.07));
 }else if(a.type==='cyl'||a.type==='cone'){const n=16,top=[],bottom=[];for(let i=0;i<n;i++){const f=i*TAU/n;bottom.push(p(Math.cos(f)*a.sx/2,-a.sy/2,Math.sin(f)*a.sz/2));top.push(a.type==='cone'?p(0,a.sy/2,0):p(Math.cos(f)*a.sx/2,a.sy/2,Math.sin(f)*a.sz/2));}for(let i=0;i<n;i++){const j=(i+1)%n,angle=(i+.5)*TAU/n+a.angle;if(Math.cos(angle)*Math.sin(yaw)+Math.sin(angle)*Math.cos(yaw)>0)poly([bottom[i],bottom[j],top[j],top[i]],shade(a.hex,lum*(.76+.1*Math.cos(angle))));}if(a.type==='cyl')poly(top,shade(a.hex,lum*1.05));
 }else{const rx=Math.max(.7,a.sx*H/span*.5),ry=Math.max(.6,(a.sy*Math.cos(elev)+a.sz*Math.sin(elev))*H/span*.4);cx.beginPath();cx.ellipse(center.x,center.y,rx,ry,0,0,TAU);const grad=cx.createRadialGradient(center.x-rx*.2,center.y-ry*.4,0,center.x,center.y,Math.max(rx,ry));grad.addColorStop(0,shade(a.hex,1.05));grad.addColorStop(1,shade(a.hex,.83));cx.fillStyle=grad;cx.fill();}}
}
function clearInput(){keys={};mouse=null;target=null;player.destKey='';}
function nearestNode(){return nodes.filter(n=>n.left>0).sort((a,b)=>dist(player,a)-dist(player,b))[0]||nodes[0];}
function goal(){const c=cfg();if(state.done)return {text:'この島は完成！ 航路から次の旅へ',target:null};if(!state.hint)return {text:'流木のそばで、資材を回収',target:nearestNode()};if(state.hint===1)return {text:'資材を、加工台に運ぼう',target:c.drop};if(state.hint===2){if(player.parts>0)return {text:'できた部品を、港から出荷',target:c.sell};return {text:'加工台で、部品を受け取ろう',target:c.drop};}if(state.hint===3&&state.till)return {text:'金色のコインを受け取ろう',target:c.cash};if(state.specialTill>0)return {text:'注文船の報酬を回収しよう',target:specialCash};if(state.till>=60)return {text:'港に、売上がたまっている',target:c.cash};if(state.money>=40&&!state.pack)return {text:'丸い札の上で、荷かごを大きく',target:upgrades[0]};if(state.island===1&&!state.bridge&&state.money>=90)return {text:'近道の橋で、運搬を効率よく',target:upgrades[5]};if(state.money>=100&&!state.courier)return {text:'配達係に、出荷を任せよう',target:upgrades[3]};if(state.money>=160&&!state.gatherer)return {text:'回収係を迎え、自分は島の修理へ',target:upgrades[4]};if(player.parts>0){if(orderActive())return {text:'注文船が到着！ 青い桟橋へ',target:special};if(state.mission<c.target)return {text:'部品を届けて、'+c.goal,target:c.repair};return {text:'部品を出荷し、次の注文船に備えよう',target:c.sell};}if(player.raw>0||mill.parts>0)return {text:'加工台で、部品をつくろう',target:c.drop};if(state.mission>=c.target&&state.specialCount<c.orders)return {text:orderActive()?'注文船へ、残りの部品を届けよう':'次の船に向けて、部品を用意しよう',target:orderActive()?special:c.drop};return {text:'集めて、運んで、島を直そう',target:state.gatherer?c.drop:nearestNode()};}
function update(dt){if(paused)return;t+=dt;if(t>toastUntil)$('toast').classList.remove('show');if(!state.done)state.elapsed+=dt;else{state.finishTimer+=dt;if(state.finishTimer>2&&!clearShown){clearShown=true;showResult();return;}}
 let dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0),dy=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0);if(mouse?.drag){dx=clamp((mouse.x-mouse.sx)/47,-1,1);dy=clamp((mouse.y-mouse.sy)/47,-1,1);if(hypot(dx,dy)<.12)dx=dy=0;}const speed=4.8+state.speed*.5;if(dx||dy){target=null;player.destKey='';const wx=Math.cos(yaw)*dx+Math.sin(yaw)*dy/Math.sin(elev),wz=-Math.sin(yaw)*dx+Math.cos(yaw)*dy/Math.sin(elev);move(player,wx,wz,dt,speed*Math.min(1,hypot(dx,dy)));}else if(target){if(routeTo(player,target,dt,speed))target=null;}else player.moving=false;
 for(const n of nodes){n.flash=Math.max(0,n.flash-dt);if(n.left===0){n.regen-=dt;if(n.regen<=0){n.left=24;n.regen=0;particle(n.x,.4,n.z,'#e3cea1',5);}}}
 gather(player,dt,true);crafting(dt);transfers(dt);staff(dt);sell(dt);payments(dt);
 for(const f of flies)f.t+=dt;flies=flies.filter(f=>f.t<f.dur);for(const s of sparks){s.life-=dt;s.x+=s.vx*dt;s.z+=s.vz*dt;s.y+=s.vy*dt;s.vy-=8*dt;}sparks=sparks.filter(s=>s.life>0).slice(-300);for(const l of labels){l.life-=dt;l.y+=dt*.5;}labels=labels.filter(l=>l.life>0);for(const r of rings)r.t+=dt;rings=rings.filter(r=>r.t<.65);
 cam.x=lerp(cam.x,clamp(player.x*.62,-3.9,4.5),1-Math.exp(-dt*4));cam.z=lerp(cam.z,clamp(player.z*.68,-4.5,3),1-Math.exp(-dt*4));camera();const g=goal();if(g.text!==lastGoal){$('objective').textContent=g.text;lastGoal=g.text;}$('islandName').textContent=(state.island+1)+' / 3 · '+cfg().name;$('missionHud').textContent=cfg().goal+'　'+state.mission+' / '+cfg().target+(cfg().orders?'　注文 '+state.specialCount+' / 3':'');$('hint').style.opacity=hasInput?'0':'1';saveClock+=dt;if(saveClock>4){saveClock=0;save();}}
function text(str,x,y,size=14,color='#fff9db',stroke='#426d72'){ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`900 ${size}px ui-rounded,"Yu Gothic",Meiryo,sans-serif`;ctx.lineJoin='round';if(stroke){ctx.lineWidth=4;ctx.strokeStyle=stroke;ctx.strokeText(str,x,y);}ctx.fillStyle=color;ctx.fillText(str,x,y);}
function label(p,str,y=.32,color='#fff6dc',size=13){const s=project(p.x,y,p.z);text(str,s.x,s.y,size,color);}
function arrow(dest){if(!dest)return;let p=project(dest.x,.4,dest.z);const real={...p};p.x=clamp(p.x,28,W-28);p.y=clamp(p.y,156,H-60);const off=p.x!==real.x||p.y!==real.y;ctx.save();ctx.translate(p.x,p.y-26+Math.sin(t*5)*5);if(off)ctx.rotate(Math.atan2(real.y-H*.5,real.x-W*.5)-Math.PI/2);ctx.fillStyle='#ffdf87';ctx.strokeStyle='#fff9de';ctx.lineWidth=2.5;ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(-7,-22);ctx.lineTo(7,-22);ctx.lineTo(7,-9);ctx.lineTo(15,-9);ctx.lineTo(0,7);ctx.lineTo(-15,-9);ctx.lineTo(-7,-9);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
function drawOverlay(){ctx.setTransform(DPR,0,0,DPR,0,0);ctx.clearRect(0,0,W,H);const c=cfg();for(const p of upgrades)if(p.show()){const s=project(p.x,.3,p.z);text(p.title(),s.x,s.y-7,12,'#315a5c','#f8ebc6');text('✦ '+Math.max(0,p.cost()-(state.paid[p.id]||0)),s.x,s.y+10,13,'#796039','#fff1c8');}
 label(c.drop,'加工');label(c.sell,'出荷');label(c.repair,state.mission===c.target?'部品完了':'修理 '+state.mission+'/'+c.target,.3,'#fff2c8',12);if(state.till)label(c.cash,'+'+state.till,.7,'#fff0a5');if(state.specialTill)label(specialCash,'+'+state.specialTill,.7,'#fff0a5');if(state.island===2){let msg=state.specialCount>=3?'注文完了':orderActive()?'注文 '+state.specialProgress+'/'+orderSize():'次の船 '+Math.ceil(45-state.elapsed%45)+'秒';label(special,msg,.4,'#e9ffff',12);}if(dist(player,c.drop)<3&&(mill.raw||mill.parts))label(c.mill,'資材 '+mill.raw+' → 部品 '+mill.parts,2.9,'#fff2bf',12);
 const count=player.raw+player.parts;if(count){const p=project(player.x,2.15+Math.min(20,count)*.19,player.z);text(count+' / '+capacity(),p.x,p.y,12,count>=capacity()?'#ffe0a1':'#fff9df');}for(const n of nodes)if(!n.left)label(n,'漂着まで '+Math.ceil(n.regen)+'秒',.8,'#fcf2d2',11);
 for(const l of labels){const p=project(l.x,l.y,l.z);ctx.globalAlpha=Math.min(1,l.life*2);text(l.text,p.x,p.y,18,l.color);}ctx.globalAlpha=1;for(const r of rings){const p=project(r.x,.2,r.z);ctx.strokeStyle='#fff3bb';ctx.globalAlpha=1-r.t/.65;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(p.x,p.y,12+r.t*70,7+r.t*35,0,0,TAU);ctx.stroke();}ctx.globalAlpha=1;arrow(goal().target);
 const pp=project(player.x,.2,player.z);ctx.strokeStyle='#fff7dabb';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(pp.x,pp.y,17,10,0,0,TAU);ctx.stroke();if(target){const p=project(target.x,.2,target.z);ctx.beginPath();ctx.arc(p.x,p.y,8,0,TAU);ctx.stroke();}if(mouse?.drag){const dx=mouse.x-mouse.sx,dy=mouse.y-mouse.sy,k=Math.min(1,43/(hypot(dx,dy)||1));ctx.fillStyle='#254d6536';ctx.strokeStyle='#fff8dcb0';ctx.lineWidth=3;ctx.beginPath();ctx.arc(mouse.sx,mouse.sy,54,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#fff5dce8';ctx.beginPath();ctx.arc(mouse.sx+dx*k,mouse.sy+dy*k,22,0,TAU);ctx.fill();}}
function render(){for(const g of Object.values(geom))g.dynamic=[];drawDynamic();if(softwareContext){fallbackRender();drawOverlay();return;}for(const g of Object.values(geom)){gl.bindBuffer(gl.ARRAY_BUFFER,g.db);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(g.dynamic),gl.DYNAMIC_DRAW);}gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.bindFramebuffer(gl.FRAMEBUFFER,fbo);gl.viewport(0,0,1024,1024);gl.clear(gl.DEPTH_BUFFER_BIT);drawPass(depthShader,lightVP);gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.35,.67,.71,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);drawPass(shader,vp);drawOverlay();}
function inputStart(){if(!hasInput){hasInput=true;canvas.focus({preventScroll:true});sound('part');}}
canvas.addEventListener('pointerdown',e=>{if(paused||mouse)return;e.preventDefault();inputStart();canvas.setPointerCapture(e.pointerId);mouse={id:e.pointerId,sx:e.clientX,sy:e.clientY,x:e.clientX,y:e.clientY,drag:false};target=null;player.destKey='';});canvas.addEventListener('pointermove',e=>{if(!mouse||mouse.id!==e.pointerId)return;mouse.x=e.clientX;mouse.y=e.clientY;if(hypot(mouse.x-mouse.sx,mouse.y-mouse.sy)>7)mouse.drag=true;});canvas.addEventListener('pointerup',e=>{if(!mouse||e.pointerId!==mouse.id)return;if(!mouse.drag){const p=unproject(e.clientX,e.clientY);p.x=clamp(p.x,-8,8);p.z=clamp(p.z,-8,8);target=p;player.destKey='';}mouse=null;});canvas.addEventListener('pointercancel',clearInput);canvas.addEventListener('lostpointercapture',()=>mouse=null);canvas.addEventListener('contextmenu',e=>e.preventDefault());addEventListener('blur',clearInput);addEventListener('pagehide',save);addEventListener('visibilitychange',()=>{if(document.hidden){save();clearInput();}});
function openPanel(mode,html){panelMode=mode;paused=true;clearInput();$('sheet').innerHTML=html;$('panel').hidden=false;save();}
function focusPanel(){const b=$('sheet').querySelector('button:not(:disabled)');b?.focus();}
function closePanel(){paused=false;$('panel').hidden=true;panelMode='';clearInput();canvas.focus({preventScroll:true});}
const timeText=secs=>Math.floor(secs/60)+'分'+String(Math.floor(secs%60)).padStart(2,'0')+'秒';
function showSettings(){openPanel('settings',`<div class="eyebrow">ISLAND WORKSHOP</div><h2 id="panelTitle">潮風工房</h2><p>近づいて集め、加工して部品へ。<br>出荷で得たコインは、丸い札の上で投資。<br>修理場所に部品を届けると、島が復旧します。</p><button id="resume" class="primary wide">ゲームに戻る</button><button id="map" class="wide">航路と持ちもの</button><button id="sound" class="wide">効果音：${meta.sound?'ON':'OFF'}</button><button id="restart" class="wide danger">この島だけをやり直す</button><hr class="divider"><p class="muted">保存はこのブラウザ内のみ。広告・課金・プレイデータの外部送信なし。ブラウザの保存データを消すと進行は失われます。${meta.legacy?'<br>旧版の記録は変更せず保管しています。':''}</p>`);$('resume').onclick=closePanel;$('map').onclick=()=>showRoute();$('sound').onclick=()=>{meta.sound=!meta.sound;$('sound').textContent='効果音：'+(meta.sound?'ON':'OFF');save();};$('restart').onclick=()=>{if(confirm('この島の資金・設備・在庫をリセットします。解放した道具と復旧記録は残ります。続けますか？')){const i=state.island,tool=state.tool;closePanel();resetRun(i,tool);}};focusPanel();}
function showResult(){const all=meta.completed.every(Boolean);openPanel('result',`<div class="eyebrow">${all?'VOYAGE COMPLETE':'ISLAND RESTORED'}</div><h2 id="panelTitle">${all?'3つの島に、灯がともった':cfg().name+'、復旧！'}</h2><div class="souvenir" aria-hidden="true">${state.island===0?'⛵':state.island===1?'⚙':'✦'}</div><p>${cfg().done}</p><p class="muted">記念品「${cfg().relic}」を記録。<br>今回の作業：${timeText(state.elapsed)} ・ 出荷：${state.sold}個<br>${state.island===0?'荷かごと携帯モーターを解放。':state.island===1?'修理キットを解放。':'同じ島も、違う道具でまた遊べます。'}</p><button id="next" class="primary wide">${all?'航路を振り返る':'次の島へ出発する'}</button><button id="stay" class="wide">完成した島を歩く</button>`);$('next').onclick=()=>showRoute(Math.min(2,state.island+1));$('stay').onclick=closePanel;focusPanel();}
function showRoute(choice=null){chosenIsland=choice??(state.done?Math.min(2,state.island+1):state.island);chosenTool=state.tool;if(!meta.unlocked.includes(chosenTool))chosenTool='none';renderRoute();}
function renderRoute(){const completed=meta.completed.filter(Boolean).length;openPanel('route',`<div class="eyebrow">YOUR VOYAGE · ${completed} / 3</div><h2 id="panelTitle">次は、どの島へ？</h2><div class="routes">${STAGES.map((s,i)=>`<button data-island="${i}" class="${chosenIsland===i?'selected':''}" ${i>unlockIndex()?'disabled':''}><b>${meta.completed[i]?'✓':i+1}</b>${s.name}<br>${i>unlockIndex()?'未開通':meta.best[i]!==null?timeText(meta.best[i]):'未復旧'}</button>`).join('')}</div><p>${STAGES[chosenIsland].story}</p><div class="eyebrow">持ちこむ道具は、ひとつ</div><div class="gear">${meta.unlocked.map(k=>`<button data-tool="${k}" class="${chosenTool===k?'selected':''}"><strong>${TOOLS[k].name}</strong><span>${TOOLS[k].desc}</span></button>`).join('')}</div><p class="muted">出発すると、現場の資金・設備・在庫は初期状態に。道具・復旧した島・記念品は残ります。${meta.legacy?'旧版からの荷かごを利用できます。':''}</p><button id="depart" class="primary wide">${chosenIsland===state.island?'この島を最初から':'この島へ出発'}</button><button id="back" class="wide">いまの島へ戻る</button>`);for(const b of $('sheet').querySelectorAll('[data-island]'))b.onclick=()=>{chosenIsland=Number(b.dataset.island);renderRoute();};for(const b of $('sheet').querySelectorAll('[data-tool]'))b.onclick=()=>{chosenTool=b.dataset.tool;renderRoute();};$('depart').onclick=()=>{if(!state.done&&state.elapsed>10&&!confirm('進行中の島を離れます。この島の設備・資金・在庫は初期状態になります。出発しますか？'))return;const i=chosenIsland,tool=chosenTool;if(i>unlockIndex()||!meta.unlocked.includes(tool))return;closePanel();resetRun(i,tool);};$('back').onclick=closePanel;focusPanel();}
$('menuBtn').onclick=showSettings;
addEventListener('keydown',e=>{if(paused&&e.code==='Tab'){const list=[...$('sheet').querySelectorAll('button:not(:disabled)')];if(list.length){const i=list.indexOf(document.activeElement),n=(i+(e.shiftKey?-1:1)+list.length)%list.length;e.preventDefault();list[n].focus();}return;}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(e.code)){e.preventDefault();if(!paused){keys[e.code]=true;target=null;inputStart();}}if(e.code==='Escape'){if(paused)closePanel();else showSettings();}});addEventListener('keyup',e=>keys[e.code]=false);
load();buildStatic();cashUpdate();camera();update(0);if(state.done){clearShown=true;showResult();}else toast(legacyNotice?'旧版の記録を保管し、荷かご付きで新しい航海を開始します':cfg().story,4.5);save();
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();save();clearInput();paused=true;$('errorDetail').textContent='画面を再読み込みすると、保存した位置から再開できます。';$('error').hidden=false;});
let last=performance.now();function loop(now){const dt=clamp((now-last)/1000,0,.2);last=now;if(!document.hidden){const n=Math.max(1,Math.ceil(dt/.025));for(let i=0;i<n;i++)update(dt/n);render();}requestAnimationFrame(loop);}render();requestAnimationFrame(loop);

})();
